### ISSUE TITLE
Multiple select: selection reset if selecting after filtering

### ISSUE THREAD

**Issue by bartvanb** [shafi-sahal/MatSelectSearch#10]
First of all, nice extension to Angular!

My issue is best illustrated with example steps. If I use your example code with `[hasSelectAll]="true"`, the following happens:

1. Select a country (e.g. Afghanistan)
2. Enter search text that will eliminate Afghanistan from search options (e.g. 'Alger')
3. Select another country (e.g. Algeria)
4. Remove search term. 

At this point, the selection in my example will be only `['Algeria']` where I expected `['Afghanistan', 'Algeria']`.

Would it be possible to keep the original selection and extend it with the newly selected countries?

**Comment by shafi-sahal** [comment]
Thanks for reporting the issue!!
Working on it...

**Comment by shafi-sahal** [comment]
The problem is due to angular resetting the value of the selected items. This happens because mat-select is not configured for searching the options. mat-select-search is returning a new list for every new key and when we select an item in the new list, the items previously selected are removed from the value. I am trying to come up with a workaround. Meanwhile, if you got an idea or suggestions never hesitate to tell me.

**Comment by shafi-sahal** [comment]
The problem is due to angular resetting the value of the selected items. This happens because mat-select is not configured for searching the options. mat-select-search is returning a new list for every new key and when we select an item in the new list, the items previously selected are removed from the value. I am trying to come up with a workaround. Meanwhile, if you got an idea or suggestions never hesitate to tell me.

**Comment by bartvanb** [comment]
I haven't ever looked in detail at `mat-select` so don't know how to fix it. 
Perhaps [this Stackblitz](https://stackblitz.com/edit/angular-searchable-multiselect-select?file=app%2Fselect-custom-trigger-example.html) might help you. The dropdown in there is also `mat-select`-based and remembers the selection after entering search text.

**Comment by shafi-sahal** [comment]
Ok, I will check it

**Comment by shafi-sahal** [comment]
Hi bartvanb. Sorry for the late release. I have fixed the issue. Test if it is working nicely for you.

**Comment by Malakian96** [comment]
This fix isn't working in v. 1.2.5
